### PR TITLE
Mobile

### LINKED ISSUE #88: [Frontend] mobile support
home page and stats page are complete but may need some changes fi designs are updated, contribute page has not been started.

### PR DESCRIPTION
**Pull request by CJ-Rose**
- [x] update mobile header with drop-down links
- [x] restyle contribution cards without images
- [x] update Home and Stats page layouts for new cards
- [x] fix InfoContainer mobile view
- [ ] ~adjustments for Contribute Page mobile view (with canvas)~  will do this after canvas is merged
- [x] implement circuit selector on Stats Page
- [ ] ~pagination of contributions on Stats Page~  will do this in a separate PR
- [x] add new FAQ text

### CODE REVIEW

**Comment by vivianjeng** [comment]
截圖 2023-09-23 下午3 25 55

I want to note here that the **What is UniRep ceremony?** is not aligned.

**Comment by CJ-Rose** [comment]
@vivianjeng 

> I want to note here that the What is UniRep ceremony? is not aligned.

when did you see this? bc i fixed it two days ago, this is what i see in the current deployment:

Screenshot 2023-09-23 at 4 27 16 PM

Screenshot 2023-09-23 at 6 15 20 PM

**Comment by ChialiT** [comment]
image


looks good to me.
I will just size down the logo in the footer, about 64px.
and add more padding at bottom.

**Review by ChialiT — COMMENTED** [review]
small adjustment suggested.

**Comment by kittybest** [comment]
image
I think under some size it lost some alphabets, but this is just a small problem.
image
Another small problem as in the picture.

And I suggest that we could set `cursor: pointer` to faqItem styling.

**Comment by CJ-Rose** [comment]
- added smaller logo and more spacing to mobile footer
- added `cursor: pointer` to FAQ
- fixed `max-width` to constrain content on large screens
- updated Home and Stats pages to be more responsive for smaller screen sizes, looking good on phones and tablets

-- Contribute page styling still needs attention in a separate PR after canvas is merged

**Review by kittybest — APPROVED** [review]

**Pull request merged**
