### PR TITLE
add popup box

### PR DESCRIPTION
**Pull request by kittybest**
- create `Popup` component 
- read gist post response, create the post url, and put it into popup box
- read twitter post url from the return url, and put it into popup box

### CODE REVIEW

**Comment by vivianjeng** [comment]
can it also solves popup to gist post?
and the gist post is now **secret**
截圖 2023-10-05 上午10 21 37

I think it should be public

**Comment by kittybest** [comment]
> can it also solves popup to gist post? and the gist post is now **secret** 截圖 2023-10-05 上午10 21 37
> 
> I think it should be public

I think the popup to gist post works? oh but it's private so I need to make them public right? I think is the problem of the previous PR #99. I will edit there.

== UPDATED ==
I think it's default public, so no worry.

**Comment by ChialiT** [comment]
the popup for twitter doesn't work.
and it has weird behavior, when I clicked "post on twitter", UI show me the authorization, then UI bring me back to the "offline page" and then jump back to the simulator page.

and for the twitter text:

image


remove the "generate your verse...unirep protocol" from the text.
but leave that only to the meta description.

**Comment by kittybest** [comment]
Problem found: gist will post without including contributionHashes since the ceremony is not loaded yet. Will fix it later.
(--> need to make sure the contributionHashes are really loaded before post.)

**Comment by kittybest** [comment]
- Fix the post on gist bug (= if post on gist without having access_token before, it will oauth first, and back to the page to post, but since the contributionHashes are not loaded yet, so the post only has introduction without hashes.)
  - might look like a dummy solution... but this is the safest way, I implement another solution in another branch, but still not perfect enough
- I found the server will crash if twitter post return error messages, fixed. **Need to re-deploy the backend**
- remove `github name` return on URL while coming back from oauth
- **Need to check if other oauth thing will cause server crash.** --> but not in this PR, since it's a general problem we need to prevent, this PR might not be merged too if someone disagree to add this feature.

**Comment by ChialiT** [comment]
x popup works well on desktop, i think my desktop browser remember my twitter auth token.
on the mobile, user is require to login but I think its my browser issue.
but its works!


image
there is very thin line on the right side of canvas, anyway we can get rid off?

**Review by ChialiT — APPROVED** [review]

**Comment by ChialiT** [comment]
there is few redirect ui under the overlay, I think its ok for now.

**Pull request merged**
