### PR TITLE
chore(frontend): add styling for cli code block, fix instrusction

### PR DESCRIPTION
**Pull request by vivianjeng**
- remove install npm package (not required, it will be installed if executing `npx trusted-setup <url>`
- add styling for cli code block 
截圖 2023-10-07 上午10 52 05

### CODE REVIEW

**Review by CJ-Rose — APPROVED** [review]

**Comment by vivianjeng** [comment]
I think the 
https://github.com/Unirep/trusted-setup/blob/23b738b65fbcf238b24241910a2d3f77953b57c6/packages/frontend/src/pages/contribute.css#L57-L63

doesn't have to be `width: 550px;`

so it can show the whole command in one line 

截圖 2023-10-07 下午1 43 49

**Comment by kittybest** [comment]
> I think the
> 
> https://github.com/Unirep/trusted-setup/blob/23b738b65fbcf238b24241910a2d3f77953b57c6/packages/frontend/src/pages/contribute.css#L57-L63
> 
> doesn't have to be `width: 550px;`
> 
> so it can show the whole command in one line
> 
> 截圖 2023-10-07 下午1 43 49

The `width: 550px` is used to align the content and the image, and to fix the position of the words. 
But we could still adjust a little bit to let it fit in.

**Comment by kittybest** [comment]
image
But question, should it look like this? @CJ-Rose

**Comment by CJ-Rose** [comment]
@kittybest you're asking about the image? yes, that's how i meant it to look...i like this a lot better than the old way, where the image was just sitting off to the side -- and esp how it was hanging down there alone at the bottom on tablet screen. but i left the old styling intact, can change it back if you guys don't like it.

**Comment by vivianjeng** [comment]
I know it's 560px now but it is still two lines...

> image But question, should it look like this? @CJ-Rose

it needs to be at least 576px to be one line 

and I disabled the width it can still be like
截圖 2023-10-07 晚上9 24 21

**Comment by kittybest** [comment]
> I know it's 560px now but it is still two lines...
> 
> > image But question, should it look like this? @CJ-Rose
> 
> it needs to be at least 576px to be one line
> 
> and I disabled the width it can still be like 截圖 2023-10-07 晚上9 24 21

ah I adjust it to 560px is because on my computer 560px is enough to make it in the same line like this ⬇️
image
But if 576 is the min pixel it needs to fit in one line on your computer, it could be changed to 576px, since `576*2=1152px` are still inside the max-width `1310px`.

However should it be two columns just like on Figma or you think one column like this is better? @CJ-Rose ? How does Chiali say?

**Comment by ChialiT** [comment]
I think the "copy" icon should locate at right side, it seems more like common pattern.
like the code block in the readme, https://github.com/Unirep/create-unirep-app

anyway we can make that?

**Review by ChialiT — COMMENTED** [review]
if we can make the icon position on the right side like typical code block, it will be great!

**Comment by CJ-Rose** [comment]
> if we can make the icon position on the right side like typical code block, it will be great!

@ChialiT i agree but the end of the line is hidden on mobile. if the icon is on the right side, you will not be able to see it without scrolling first. imo it's better to leave it on the left for this reason, but will change if you still want.

> However should it be two columns just like on Figma or you think one column like this is better?

@kittybest @vivianjeng i think the single line is ideal when possible.

**Comment by vivianjeng** [comment]
@CJ-Rose we can add

```css
.cli {
   word-break: break-word;
}
```

to show all text? like this

截圖 2023-10-08 晚上7 28 43


yeah I agree with it to be one line

but not sure if https://github.com/Unirep/trusted-setup/pull/126#issuecomment-1751610269 breaks something
for me it works well

**Review by ChialiT — APPROVED** [review]

**Comment by ChialiT** [comment]
we can merge it with icon on the left, its less friendly pattern but its not a deal breaker

**Pull request merged**
